application: simpview
version: 0c
runtime: python27
api_version: 1
threadsafe: true

handlers:
 - url: /
   static_files: static/html/main.html
   upload: static/html/main.html
   
 - url: /([^/.]+)\.([^/.]+)
   static_files: static/\2/\1.\2
   upload: static/.*

 - url: /upload
   static_files: static/html/upload.html
   upload: static/html/upload.html
   login: required

 - url: /_ah/login_required
   script: login.app

 - url: /banner
   script: banner.app

 - url: /uploadbg
   script: uploadbg.app

 - url: /download
   script: DownloadRedirector.app

 - url: /download/[^/]+/[^/]+
   script: DownloadHandler.app

 - url: /query
   script: QueryByName.app


builtins:
 - appstats: on

error_handlers:
 - file: static/html/default_error.html

 - error_code: over_quota
   file: static/html/over_quota.html

 - error_code: dos_api_denial
   file: static/html/dos_api_denial.html